services:

  QAlliance\CrontabManager\Writer:
    arguments:
      - '@acrnogor_crontab_manager.user'

  acrnogor_crontab_manager.command.crontab_update_command:
    class: Acrnogor\CrontabManagerBundle\Command\CrontabUpdateCommand
    arguments:
      - '@acrnogor_crontab_manager.manager.crontab'
    tags:
      - { name: 'console.command' }
